public enum Position {
    GOALKEEPER,
    RIGHT_BACK,
    LEFT_BACK,
    SWEEPER,
    CENTRAL_BACK,
    DEFENSIVE_MIDFIELDER,
    WINGER,
    CENTRAL_MIDFIELDER,
    STRIKER,
    CENTRAL_ATTACKING_MIDFIELDER
}